# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
    type: mariadb:10.4
    disk: 2048

cache:
    type: redis:5.0

#elasticsearch:
#    type: elasticsearch:7.2
#    disk: 1024
